trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.14'
  displayName: "Set Python Version"

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: "Install Dependencies"


- script: |
    python -m behave --tags=@iosApp --junit --junit-directory test-results/ios
  displayName: "Run iOS App Automation Tests"
  env:
    LT_USERNAME: $(LT_USERNAME)
    LT_ACCESS_KEY: $(LT_ACCESS_KEY)

- script: |
    python -m behave --tags=@androidApp --junit --junit-directory test-results/android
  displayName: "Run Android App Automation Tests"
  condition: succeededOrFailed()
  env:
    LT_USERNAME: $(LT_USERNAME)
    LT_ACCESS_KEY: $(LT_ACCESS_KEY)

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/test-results/**/*.xml'
    testRunTitle: 'LambdaTest Results'
  condition: succeededOrFailed()

- task: configuration@1
  inputs:
    connection: 'testing'
    isTunnelActivate: false
    isAppAutomate: true
    isSmartUI: true


- task: LambdatestResults@1
